baseURL = 'https://xuxuejie.cn/'
locale = 'zh'
title = 'AI小o'
theme = 'PaperMod'
hasCJKLanguage = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false

[pagination]
  pagerSize = 10

[taxonomies]
  category = 'categories'
  tag = 'tags'

[permalinks]
  pages = '/:slug/'
  categories = '/category/:slug/'
  tags = '/tag/:slug/'

[[menu.main]]
  name = '归档'
  url = '/archives/'
  weight = 1

[[menu.main]]
  name = '分类'
  url = '/categories/'
  weight = 2

[[menu.main]]
  name = '标签'
  url = '/tags/'
  weight = 3

[[menu.main]]
  name = '友链'
  url = '/links/'
  weight = 4

[params]
  defaultTheme = "auto"
  description = ""
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowToc = true
  TocOpen = true
  UseHugoToc = true
  comments = false

[params.homeInfoParams]
  Title = "AI小o"
  Content = ""

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/JsnowyXu"

[[params.socialIcons]]
  name = "orcid"
  url = "https://orcid.org/0000-0003-4890-2110"

[[params.socialIcons]]
  name = "email"
  url = "mailto:x_xuejie@buaa.edu.cn"
